imports:
    - { resource: parameters.yml }
    - { resource: parameters_local.yml }
    - { resource: security.yml }
    - { resource: partial/framework.yml }
    - { resource: partial/assetic.yml }
    - { resource: partial/doctrine.yml }
    - { resource: partial/doctrine_mongodb.yml }
    - { resource: partial/swiftmailer.yml }
    - { resource: partial/twig.yml }
    - { resource: partial/rms_push_notifications.yml }
