parameters:
#    zen_core.example.class: Zen\CoreBundle\Example

services:
#    zen_core.example:
#        class: %zen_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
