parameters:
    assetic.filter.compass.images_dir: %kernel.root_dir%/../web/images
    assetic.filter.compass.http_path:  /images

assetic:
    debug:          %kernel.debug%
    use_controller: false
#    bundles:        ["MHSkeletonBundle", "MopaBootstrapBundle"]
    #java: /usr/bin/java
#    filters:
#        cssrewrite: ~
#        sass: ~
#        compass:
#            apply_to: "\.(scss|sass)$"
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
